### ISSUE TITLE
Exception when executing in Amazon Ubuntu ec2 

### ISSUE THREAD

**Issue by mdmota** [andrei-m-code/net-core-html-to-image#11]
When running on my computer it works normal.
When running on the server amazon linux returns the exception:
  at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at CoreHtmlToImage.HtmlConverter.FromUrl(String url, Int32 width, ImageFormat format, Int32 quality)
   at CoreHtmlToImage.HtmlConverter.FromHtmlString(String html, Int32 width, ImageFormat format, Int32 quality)

**Comment by mdmota** [comment]
@andrei-m-code
